#!/usr/bin/env bun
/**
 * T18 — regenerate `.pi/lib/schema.generated.ts` from the L1 pydantic schema.
 *
 * C5: the pydantic record models are the single schema source. This build step
 * turns `insight_kit.platform.gate.cli export-schema` JSON into a committed TS module the
 * pi extension wraps as TypeBox `parameters`. Never hand-edit the generated file.
 *
 * Run: `bun run deploy/scripts/gen-pi-schema.ts`
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const repoRoot = join(import.meta.dir, "../..");

const raw = execFileSync(
	"uv",
	["run", "python", "-m", "insight_kit.platform.gate.cli", "export-schema"],
	{ cwd: repoRoot, encoding: "utf-8" },
);

// Parse + re-stringify so a malformed export fails the build loudly.
const schemas = JSON.parse(raw);

const out = `// GENERATED by scripts/gen-pi-schema.ts — DO NOT EDIT BY HAND.
// Single schema source (C5): the insight_kit.gate.schema pydantic models.
// Regenerate after any schema change: bun run scripts/gen-pi-schema.ts

/** Pydantic-derived, $defs-inlined JSON Schema for each tool's params (C5). */
export const recordParamSchemas = ${JSON.stringify(schemas, null, 2)} as const;
`;

const target = join(repoRoot, ".pi", "lib", "schema.generated.ts");
writeFileSync(target, out, "utf-8");
console.log(`wrote ${target}`);
