// GENERATED by scripts/gen-pi-schema.ts — DO NOT EDIT BY HAND.
// Single schema source (C5): the insight_kit.gate.schema pydantic models.
// Regenerate after any schema change: bun run scripts/gen-pi-schema.ts

/** Pydantic-derived, $defs-inlined JSON Schema for each tool's params (C5). */
export const recordParamSchemas = {
  "claim": {
    "additionalProperties": false,
    "properties": {
      "audience": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Audience"
      },
      "cites": {
        "items": {
          "type": "string"
        },
        "title": "Cites",
        "type": "array"
      },
      "claim_id": {
        "description": "Stable ID matching ^[A-Z]{2,5}-(D|R|C|I|V|X|ETL_[RCM])-\\d{3,}$",
        "title": "Claim Id",
        "type": "string"
      },
      "coverage": {
        "anyOf": [
          {
            "additionalProperties": false,
            "description": "V14 — input-coverage metadata for a claim.\n\nn: sample size of the claim's inputs (rows / observations behind the value).\npartial_period: True when the input window is an incomplete calendar period\n                (e.g. month-to-date treated as if it were a full month).\n\nOptional: when absent the gate cannot assess coverage. When present and\n\"thin\" (partial_period, or n < 30) a published claim MUST carry a\ncoverage_warning or it is rejected at emit (T10/V14).",
            "properties": {
              "n": {
                "anyOf": [
                  {
                    "type": "integer"
                  },
                  {
                    "type": "null"
                  }
                ],
                "default": null,
                "title": "N"
              },
              "partial_period": {
                "default": false,
                "title": "Partial Period",
                "type": "boolean"
              }
            },
            "title": "CoverageInfo",
            "type": "object"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "coverage_warning": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Coverage Warning"
      },
      "fields": {
        "additionalProperties": {
          "additionalProperties": false,
          "description": "One named field inside a claim's fields dict.\n\nvalue: the actual numeric or string value being asserted.\nfmt_hint: optional formatting hint for Evidence render (e.g. \"%.1f%%\", \"$,.0f\").",
          "properties": {
            "fmt_hint": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Fmt Hint"
            },
            "value": {
              "title": "Value"
            }
          },
          "required": [
            "value"
          ],
          "title": "FieldEntry",
          "type": "object"
        },
        "description": "Named values being asserted, each with optional fmt_hint.",
        "title": "Fields",
        "type": "object"
      },
      "input_data": {
        "description": "Optional registered-upstream fingerprint dict for input provenance (V13). Omit for draft records with no registered upstream.",
        "type": "object"
      },
      "narrative_ref": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Narrative Ref"
      },
      "selection": {
        "anyOf": [
          {
            "additionalProperties": false,
            "description": "V15 — explicit selection params for a claim.\n\nDate-window / baseline / filter / grain selections MUST be emitted as\nexplicit, structured claim fields — never left implicit in prompt text\n(RT4: an agent-chosen window/filter must not cross the gate unrecorded).\n\ndate_window: selected window, e.g. \"2026-03-01/2026-03-31\".\nbaseline:    baseline period or baseline claim_id the value is measured against.\ngrain:       aggregation grain, e.g. \"month\", \"week\", \"day\".\nfilters:     dimension filters applied, e.g. {\"channel\": \"meta\"}.",
            "properties": {
              "baseline": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "default": null,
                "title": "Baseline"
              },
              "date_window": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "default": null,
                "title": "Date Window"
              },
              "filters": {
                "additionalProperties": true,
                "title": "Filters",
                "type": "object"
              },
              "grain": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "default": null,
                "title": "Grain"
              }
            },
            "title": "SelectionParams",
            "type": "object"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "supersedes": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Supersedes"
      },
      "tier": {
        "default": "draft",
        "description": "Tier enum for claim/intervention records (C7).",
        "enum": [
          "draft",
          "published"
        ],
        "title": "ClaimTier",
        "type": "string"
      }
    },
    "required": [
      "claim_id",
      "fields"
    ],
    "type": "object"
  },
  "intervention": {
    "additionalProperties": false,
    "properties": {
      "audience": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Audience"
      },
      "cites": {
        "items": {
          "type": "string"
        },
        "title": "Cites",
        "type": "array"
      },
      "input_data": {
        "description": "Optional registered-upstream fingerprint dict for input provenance (V13). Omit for draft records with no registered upstream.",
        "type": "object"
      },
      "intent": {
        "additionalProperties": true,
        "description": "What the agent decided to do.",
        "properties": {
          "description": {
            "title": "Description",
            "type": "string"
          },
          "params": {
            "additionalProperties": true,
            "title": "Params",
            "type": "object"
          }
        },
        "required": [
          "description"
        ],
        "title": "IntentPayload",
        "type": "object"
      },
      "intervention_id": {
        "description": "Stable ID for this intervention.",
        "title": "Intervention Id",
        "type": "string"
      },
      "realized": {
        "anyOf": [
          {
            "additionalProperties": true,
            "description": "What actually happened when the intent was executed externally.\n\nstatus must be one of: applied | partial | failed  (V19).",
            "properties": {
              "details": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "default": null,
                "title": "Details"
              },
              "params": {
                "additionalProperties": true,
                "title": "Params",
                "type": "object"
              },
              "status": {
                "enum": [
                  "applied",
                  "partial",
                  "failed"
                ],
                "title": "Status",
                "type": "string"
              }
            },
            "required": [
              "status"
            ],
            "title": "RealizedPayload",
            "type": "object"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "supersedes": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Supersedes"
      },
      "tier": {
        "default": "draft",
        "description": "Tier enum for claim/intervention records (C7).",
        "enum": [
          "draft",
          "published"
        ],
        "title": "ClaimTier",
        "type": "string"
      }
    },
    "required": [
      "intent",
      "intervention_id"
    ],
    "type": "object"
  },
  "research": {
    "additionalProperties": false,
    "properties": {
      "cites": {
        "items": {
          "type": "string"
        },
        "title": "Cites",
        "type": "array"
      },
      "input_data": {
        "description": "Optional registered-upstream fingerprint dict for input provenance (V13). Omit for draft records with no registered upstream.",
        "type": "object"
      },
      "query": {
        "title": "Query",
        "type": "string"
      },
      "research_id": {
        "description": "Stable ID for this research record.",
        "title": "Research Id",
        "type": "string"
      },
      "snapshot": {
        "description": "T22/V20 — captured-results payload (query/tool/source/timestamp + data). Required and non-empty; persisted + content-addressed.",
        "type": "object"
      },
      "snapshot_ref": {
        "description": "Origin label for the captured results.",
        "title": "Snapshot Ref",
        "type": "string"
      },
      "source": {
        "title": "Source",
        "type": "string"
      },
      "supersedes": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Supersedes"
      },
      "timestamp": {
        "description": "ISO-8601 timestamp of research.",
        "title": "Timestamp",
        "type": "string"
      }
    },
    "required": [
      "query",
      "research_id",
      "snapshot",
      "snapshot_ref",
      "source"
    ],
    "type": "object"
  },
  "skill_use": {
    "additionalProperties": false,
    "properties": {
      "cites": {
        "items": {
          "type": "string"
        },
        "title": "Cites",
        "type": "array"
      },
      "input_data": {
        "description": "Optional registered-upstream fingerprint dict for input provenance (V13). Omit for draft records with no registered upstream.",
        "type": "object"
      },
      "skill_use_id": {
        "description": "Stable ID for this skill-use record.",
        "title": "Skill Use Id",
        "type": "string"
      },
      "snapshot": {
        "description": "T22/V20 — captured-results payload (query/tool/source/timestamp + data). Required and non-empty; persisted + content-addressed.",
        "type": "object"
      },
      "snapshot_ref": {
        "description": "Origin label for the captured results.",
        "title": "Snapshot Ref",
        "type": "string"
      },
      "source": {
        "title": "Source",
        "type": "string"
      },
      "supersedes": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Supersedes"
      },
      "timestamp": {
        "description": "ISO-8601 timestamp of skill invocation.",
        "title": "Timestamp",
        "type": "string"
      },
      "tool": {
        "title": "Tool",
        "type": "string"
      }
    },
    "required": [
      "skill_use_id",
      "snapshot",
      "snapshot_ref",
      "source",
      "tool"
    ],
    "type": "object"
  }
} as const;
